#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


rm -rf 0/

cp -R data/0.orig/ 0

blockMesh

makeAxialMesh -axis ROT_AXIS -wedge defaultFaces -overwrite

collapseEdges 1e-06 175 -overwrite

createPatch -overwrite

funkySetFields -time 0 
